#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use RamyHerrira\Wikilinks\Container;
use RoachPHP\Roach;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutputInterface;

$container = new Container();

$application = new Application();

Roach::useContainer($container);

$application->add(new \RamyHerrira\Wikilinks\GuessCommand());

$application->run(
    null,
    $container->get(ConsoleOutputInterface::class),
);
